import { useState } from 'react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'
import { Card, CardContent, CardHeader, CardTitle } from '../ui/Card'
import { SimulationState } from '../../types/simulation'

interface MultiVariablePlotProps {
  state: SimulationState
}

interface PlotVariable {
  key: string
  label: string
  unit: string
  color: string
  getValue: (state: SimulationState, index: number) => number
}

// Define available variables for plotting
const X_AXIS_VARIABLES: PlotVariable[] = [
  {
    key: 'time',
    label: 'Time (hours)',
    unit: 'hrs',
    color: '#888888',
    getValue: (state, index) => index * state.time_step_hours
  },
  {
    key: 'ambient_temp',
    label: 'Ambient Temperature',
    unit: '°C',
    color: '#f59e0b',
    getValue: (state, index) => state.history.ambient_temp[index] || 0
  },
  {
    key: 'gpu_utilization',
    label: 'GPU Utilization',
    unit: '%',
    color: '#3b82f6',
    getValue: (state, index) => state.history.gpu_utilization[index] || 0
  },
  {
    key: 'total_power',
    label: 'Total Power',
    unit: 'kW',
    color: '#8b5cf6',
    getValue: (state, index) => state.history.total_power[index] || 0
  }
]

const Y_AXIS_VARIABLES: PlotVariable[] = [
  {
    key: 'pue',
    label: 'PUE',
    unit: '',
    color: '#f59e0b',
    getValue: (state, index) => state.history.pue[index] || 0
  },
  {
    key: 'cooling_power',
    label: 'Cooling Power',
    unit: 'kW',
    color: '#06b6d4',
    getValue: (state, index) => state.history.cooling_power[index] || 0
  },
  {
    key: 'it_power',
    label: 'IT Power',
    unit: 'kW',
    color: '#3b82f6',
    getValue: (state, index) => state.history.it_power[index] || 0
  },
  {
    key: 'total_power',
    label: 'Total Power',
    unit: 'kW',
    color: '#8b5cf6',
    getValue: (state, index) => state.history.total_power[index] || 0
  },
  {
    key: 'gpu_utilization',
    label: 'GPU Utilization',
    unit: '%',
    color: '#10b981',
    getValue: (state, index) => state.history.gpu_utilization[index] || 0
  },
  {
    key: 'temperature',
    label: 'Zone Temperature',
    unit: '°C',
    color: '#ef4444',
    getValue: (state, index) => state.history.temperature[index] || 0
  },
  {
    key: 'cost_rate',
    label: 'Cost Rate',
    unit: '$/hr',
    color: '#22c55e',
    getValue: (state, index) => state.history.cost_rate[index] || 0
  },
  {
    key: 'carbon_rate',
    label: 'Carbon Rate',
    unit: 'kg/hr',
    color: '#84cc16',
    getValue: (state, index) => state.history.carbon_rate[index] || 0
  },
  {
    key: 'cooling_efficiency',
    label: 'Cooling Efficiency (COP)',
    unit: '',
    color: '#0ea5e9',
    getValue: (state, index) => {
      const coolingPower = state.history.cooling_power[index] || 0
      const itPower = state.history.it_power[index] || 0
      // COP = Heat Removed / Cooling Power
      // Heat removed = IT Load (since we're removing the heat generated by IT equipment)
      return coolingPower > 0 ? itPower / coolingPower : 0
    }
  },
  {
    key: 'power_density',
    label: 'Power Density',
    unit: 'kW/GPU',
    color: '#f97316',
    getValue: (state, index) => {
      const totalPower = state.history.total_power[index] || 0
      const totalGPUs = state.metrics?.total_gpus || 1
      return totalPower / totalGPUs
    }
  }
]

export function MultiVariablePlot({ state }: MultiVariablePlotProps) {
  const [xAxisVar, setXAxisVar] = useState<string>('time')
  const [selectedYVars, setSelectedYVars] = useState<string[]>(['pue', 'cooling_power', 'gpu_utilization'])

  const handleYVarToggle = (varKey: string) => {
    if (selectedYVars.includes(varKey)) {
      setSelectedYVars(selectedYVars.filter(k => k !== varKey))
    } else {
      if (selectedYVars.length < 5) {
        setSelectedYVars([...selectedYVars, varKey])
      }
    }
  }

  // Prepare data for plotting
  const dataPoints = state.history.timestamps.map((_, index) => {
    const point: any = { index }

    // Add x-axis value
    const xVar = X_AXIS_VARIABLES.find(v => v.key === xAxisVar)
    if (xVar) {
      point.x = xVar.getValue(state, index)
    }

    // Add selected y-axis values
    selectedYVars.forEach(yKey => {
      const yVar = Y_AXIS_VARIABLES.find(v => v.key === yKey)
      if (yVar) {
        point[yKey] = yVar.getValue(state, index)
      }
    })

    return point
  })

  const xVariable = X_AXIS_VARIABLES.find(v => v.key === xAxisVar)

  if (state.history.timestamps.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Multi-Variable Analysis</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-64 flex items-center justify-center text-muted-foreground">
            No data yet. Run the simulation to see analysis.
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Multi-Variable Analysis</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Controls */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* X-Axis Selection */}
          <div>
            <label className="block text-sm font-medium mb-2">X-Axis Variable</label>
            <select
              value={xAxisVar}
              onChange={(e) => setXAxisVar(e.target.value)}
              className="w-full px-3 py-2 border border-border rounded-md bg-background text-sm"
            >
              {X_AXIS_VARIABLES.map(variable => (
                <option key={variable.key} value={variable.key}>
                  {variable.label} ({variable.unit})
                </option>
              ))}
            </select>
          </div>

          {/* Y-Axis Selection */}
          <div>
            <label className="block text-sm font-medium mb-2">
              Y-Axis Variables (Select up to 5)
            </label>
            <div className="grid grid-cols-2 gap-2 max-h-48 overflow-y-auto p-2 border border-border rounded-md bg-background">
              {Y_AXIS_VARIABLES.map(variable => (
                <label
                  key={variable.key}
                  className="flex items-center space-x-2 text-sm cursor-pointer hover:bg-muted p-1 rounded"
                >
                  <input
                    type="checkbox"
                    checked={selectedYVars.includes(variable.key)}
                    onChange={() => handleYVarToggle(variable.key)}
                    disabled={!selectedYVars.includes(variable.key) && selectedYVars.length >= 5}
                    className="w-4 h-4"
                  />
                  <span className="flex items-center gap-1">
                    <span
                      className="w-3 h-3 rounded-full"
                      style={{ backgroundColor: variable.color }}
                    />
                    <span>{variable.label}</span>
                  </span>
                </label>
              ))}
            </div>
          </div>
        </div>

        {/* Chart */}
        <ResponsiveContainer width="100%" height={400}>
          <LineChart data={dataPoints} margin={{ top: 20, right: 80, bottom: 20, left: 20 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#333" />
            <XAxis
              dataKey="x"
              name={xVariable?.label}
              unit={xVariable?.unit ? ` ${xVariable.unit}` : ''}
              stroke="#888"
              type="number"
              domain={['auto', 'auto']}
            />
            {selectedYVars.map((yKey, index) => {
              const yVar = Y_AXIS_VARIABLES.find(v => v.key === yKey)
              if (!yVar) return null

              // Position Y-axes: first on left, second on right, rest hidden but scaled
              const yAxisId = `yAxis-${index}`
              const orientation = index === 0 ? 'left' : index === 1 ? 'right' : 'right'
              const hide = index > 1

              return (
                <YAxis
                  key={yAxisId}
                  yAxisId={yAxisId}
                  orientation={orientation}
                  stroke={yVar.color}
                  hide={hide}
                  label={!hide ? {
                    value: `${yVar.label}${yVar.unit ? ` (${yVar.unit})` : ''}`,
                    angle: orientation === 'left' ? -90 : 90,
                    position: orientation === 'left' ? 'insideLeft' : 'insideRight',
                    style: { fill: yVar.color }
                  } : undefined}
                />
              )
            })}
            <Tooltip
              contentStyle={{
                backgroundColor: 'hsl(var(--card))',
                border: '1px solid hsl(var(--border))',
                borderRadius: '6px'
              }}
              formatter={(value: number, name: string) => {
                const yVar = Y_AXIS_VARIABLES.find(v => v.key === name)
                return [
                  `${value.toFixed(2)}${yVar?.unit ? ` ${yVar.unit}` : ''}`,
                  yVar?.label || name
                ]
              }}
              labelFormatter={(value) => `${xVariable?.label}: ${value.toFixed(2)}${xVariable?.unit ? ` ${xVariable.unit}` : ''}`}
            />
            <Legend />
            {selectedYVars.map((yKey, index) => {
              const yVar = Y_AXIS_VARIABLES.find(v => v.key === yKey)
              if (!yVar) return null
              return (
                <Line
                  key={yKey}
                  yAxisId={`yAxis-${index}`}
                  type="linear"
                  dataKey={yKey}
                  stroke={yVar.color}
                  strokeWidth={2}
                  dot={{ fill: yVar.color, r: 3 }}
                  name={`${yVar.label}${yVar.unit ? ` (${yVar.unit})` : ''}`}
                  connectNulls
                />
              )
            })}
          </LineChart>
        </ResponsiveContainer>

        {/* Info */}
        <div className="text-xs text-muted-foreground">
          {dataPoints.length} data points • {selectedYVars.length} of 5 variables selected
        </div>
      </CardContent>
    </Card>
  )
}
